export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_ERROR = 'LOGIN_REQUEST_ERROR';

//List Unclaimed devices
export const UNCLAIMED_DEVICES_FETCH_IN_PROGRESS = 'UNCLAIMED_DEVICES_FETCH_IN_PROGRESS';
export const UNCLAIMED_DEVICES_FETCH_SUCCESS = 'UNCLAIMED_DEVICES_FETCH_SUCCESS';
export const UNCLAIMED_DEVICES_FETCH_ERROR = 'UNCLAIMED_DEVICES_FETCH_ERROR';
export const STORE_SELECTED_UNCLAIMED_DEVICES = 'STORE_SELECTED_UNCLAIMED_DEVICES';

//Config Unclaimed devices
export const CLAIM_DEVICE_CONFIG_FETCH_IN_PROGRESS = 'CLAIM_DEVICE_CONFIG_FETCH_IN_PROGRESS';
export const CLAIM_DEVICE_CONFIG_FETCH_SUCCESS = 'CLAIM_DEVICE_CONFIG_FETCH_SUCCESS';
export const CLAIM_DEVICE_CONFIG_FETCH_ERROR = 'CLAIM_DEVICE_CONFIG_FETCH_ERROR';
export const STORE_CLAIM_DEVICE_CONFIG = 'STORE_CLAIM_DEVICE_CONFIG';

//Claim devices
export const CLAIM_DEVICE_IN_PROGRESS = 'CLAIM_DEVICE_IN_PROGRESS';
export const CLAIM_DEVICE_SUCCESS = 'CLAIM_DEVICE_SUCCESS';
export const CLAIM_DEVICE_ERROR = 'CLAIM_DEVICE_ERROR';